export enum Type{
    NUMERIC,
    STRING,
    BOOLEAN,
    DOUBLE,
    CHAR,
    VOID,
    COMA
}
export enum TypeOperation{
    SUMA, RESTA, MULTIPLICACION, DIVISION, MENOSUNARIO,
    MAYOR, MENOR,MAYOR_IGUAL,MENOR_IGUAL,ADICION,SUBSTRACCION,
    OR, AND, NOT, XOR, IGUAL_IGUAL, DISTINTO, IGUAL, PARENTESIS
}
